steps:
  # Debug: show what's in the workspace
  - name: alpine
    entrypoint: sh
    args: ['-lc', 'echo "PWD=$(pwd)"; echo "--- ls -la:"; ls -la']

  # Build Docker image (explicitly point to Dockerfile at root)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f','Dockerfile',
        '-t','us-central1-docker.pkg.dev/$PROJECT_ID/daniel-100624358/assignment2:${SHORT_SHA}',
        '.'
      ]

  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/$PROJECT_ID/daniel-100624358/assignment2:${SHORT_SHA}'
      ]

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/daniel-100624358/assignment2:${SHORT_SHA}'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
